name: Java CI with Maven and Mockito

on:
  push:
    branches:
      - new-feature-obs
  pull_request:
    branches:
      - new-features-obs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 'adopt@1.18'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: 'adopt@1.18'
          maven-version: '3.8.4'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean install -B

      - name: Run tests with Maven
        run: ./mvnw test -B

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: target/surefire-reports

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: Jar File
          path: target/*.jar