name: Java CI with Maven

on:
  push:
    branches:
      - "master"
      - "develop"
      - "Feature"
      - "new-feature"
      - "new-feature-obs"
  pull_request:
    branches: ["new-feature-obs"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
